[package]
name = "flerp"
version = "0.1.1"
edition = "2021"
authors = ["Huseyn"]
description = "CLI tool that does XYZ"
license = "MIT"
repository = "https://github.com/Huseynteymurzade28/flerp"
homepage = "https://github.com/Huseynteymurzade28/flerp"
readme = "README.md"


[dependencies]
colored = "3.0.0"
